### ISSUE TITLE
?randomwalk command

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Discord-Bot-Choo-Choo#7]
I wonder if `?randomwalk` should return your specific random number pattern. If you don't have one, then it generates a random one?

In general I think we can have less text, so with nothing provided it can say:

> Generating your random walk with number number 12345 from position 181,116.

Or if you have no number:

> Picking random number 12345 from position 181,116 and generating random walk:

Or if you provide a number

> Generating random walk with number number 12345 from position 181,116.

**Comment by KobeLiesenborgs** [comment]
Implemented in f2c7118d125b11b1188ea4d3c46b8ed69e99c426
